version: "3.9"

services:

  frontend:
    build:
      context: .
      dockerfile: ./services/frontend/Dockerfile
    volumes:
      - ./services/frontend:/app
      - ./shared:/app/shared
      - /app/node_modules
    ports:
      - '5173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100

  backend:
    build:
      context: .
      dockerfile: ./services/backend/Dockerfile
    volumes:
      - ./services/backend/src:/app/src
      - ./shared:/app/shared
      - /app/node_modules
    ports:
      - '3000:3000'
