# Комманды
# docker-compose up -d --build - Пересобрать и перезапустить контейнер

version: "3.9"

services:

  frontend:
    build:
      context: .
      dockerfile: /services/frontend/Dockerfile
    volumes:
      - ./services/frontend/src:/app/src
      - ./shared:/app/shared
      - /app/node_modules
    ports:
      - '5173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100

  backend:
    build:
      context: .
      dockerfile: /services/backend/Dockerfile
    volumes:
      - ./services/backend/src:/app/src
      - ./shared:/app/shared
      - /app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - ./services/backend/.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:18.0-alpine
    container_name: postgres
    env_file:
      - ./services/backend/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network

  redis:
    image: redis:8.2.3-alpine
    container_name: redis
    env_file:
      - ./services/backend/.env
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network

volumes:
  postgres-data:
  redis-data:

networks:
  postgres-network:
  redis-network: